# Dependencies
markdown:         kramdown
highlighter:      Rouge
remote_theme:     poole/hyde

# Permalinks
permalink:        pretty

# Setup
title:            Lilbigblog
tagline:          "Lilbigmouth's tech-related blog"
description:      "Lilbigmouth's tech-related blog"
url:              https://lilbigmouth.github.io/
baseurl:          /
version:          0.1.0

author:
  name:           'lilbigmouth'
  url:            https://twitter.com/lilbigmouth

paginate:         5
